//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenAutoUpdate.GenClientAutoUpdate {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://GenClientAutoUpdate/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://GenClientAutoUpdate/", ConfigurationName="GenClientAutoUpdate.GenClientAutoUpdateSoap")]
    public interface GenClientAutoUpdateSoap {
        
        // CODEGEN: 命名空间 http://GenClientAutoUpdate/ 的元素名称 sDir 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://GenClientAutoUpdate/HelloWorld", ReplyAction="*")]
        GenAutoUpdate.GenClientAutoUpdate.HelloWorldResponse HelloWorld(GenAutoUpdate.GenClientAutoUpdate.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://GenClientAutoUpdate/ 的元素名称 sDir 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://GenClientAutoUpdate/getUpdateList", ReplyAction="*")]
        GenAutoUpdate.GenClientAutoUpdate.getUpdateListResponse getUpdateList(GenAutoUpdate.GenClientAutoUpdate.getUpdateListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://GenClientAutoUpdate/", Order=0)]
        public GenAutoUpdate.GenClientAutoUpdate.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(GenAutoUpdate.GenClientAutoUpdate.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://GenClientAutoUpdate/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sDir;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string sDir) {
            this.sDir = sDir;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://GenClientAutoUpdate/", Order=0)]
        public GenAutoUpdate.GenClientAutoUpdate.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(GenAutoUpdate.GenClientAutoUpdate.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://GenClientAutoUpdate/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdateListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUpdateList", Namespace="http://GenClientAutoUpdate/", Order=0)]
        public GenAutoUpdate.GenClientAutoUpdate.getUpdateListRequestBody Body;
        
        public getUpdateListRequest() {
        }
        
        public getUpdateListRequest(GenAutoUpdate.GenClientAutoUpdate.getUpdateListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://GenClientAutoUpdate/")]
    public partial class getUpdateListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sDir;
        
        public getUpdateListRequestBody() {
        }
        
        public getUpdateListRequestBody(string sDir) {
            this.sDir = sDir;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdateListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUpdateListResponse", Namespace="http://GenClientAutoUpdate/", Order=0)]
        public GenAutoUpdate.GenClientAutoUpdate.getUpdateListResponseBody Body;
        
        public getUpdateListResponse() {
        }
        
        public getUpdateListResponse(GenAutoUpdate.GenClientAutoUpdate.getUpdateListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://GenClientAutoUpdate/")]
    public partial class getUpdateListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GenAutoUpdate.GenClientAutoUpdate.ArrayOfString getUpdateListResult;
        
        public getUpdateListResponseBody() {
        }
        
        public getUpdateListResponseBody(GenAutoUpdate.GenClientAutoUpdate.ArrayOfString getUpdateListResult) {
            this.getUpdateListResult = getUpdateListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GenClientAutoUpdateSoapChannel : GenAutoUpdate.GenClientAutoUpdate.GenClientAutoUpdateSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenClientAutoUpdateSoapClient : System.ServiceModel.ClientBase<GenAutoUpdate.GenClientAutoUpdate.GenClientAutoUpdateSoap>, GenAutoUpdate.GenClientAutoUpdate.GenClientAutoUpdateSoap {
        
        public GenClientAutoUpdateSoapClient() {
        }
        
        public GenClientAutoUpdateSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenClientAutoUpdateSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenClientAutoUpdateSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenClientAutoUpdateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GenAutoUpdate.GenClientAutoUpdate.HelloWorldResponse GenAutoUpdate.GenClientAutoUpdate.GenClientAutoUpdateSoap.HelloWorld(GenAutoUpdate.GenClientAutoUpdate.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string sDir) {
            GenAutoUpdate.GenClientAutoUpdate.HelloWorldRequest inValue = new GenAutoUpdate.GenClientAutoUpdate.HelloWorldRequest();
            inValue.Body = new GenAutoUpdate.GenClientAutoUpdate.HelloWorldRequestBody();
            inValue.Body.sDir = sDir;
            GenAutoUpdate.GenClientAutoUpdate.HelloWorldResponse retVal = ((GenAutoUpdate.GenClientAutoUpdate.GenClientAutoUpdateSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GenAutoUpdate.GenClientAutoUpdate.getUpdateListResponse GenAutoUpdate.GenClientAutoUpdate.GenClientAutoUpdateSoap.getUpdateList(GenAutoUpdate.GenClientAutoUpdate.getUpdateListRequest request) {
            return base.Channel.getUpdateList(request);
        }
        
        public GenAutoUpdate.GenClientAutoUpdate.ArrayOfString getUpdateList(string sDir) {
            GenAutoUpdate.GenClientAutoUpdate.getUpdateListRequest inValue = new GenAutoUpdate.GenClientAutoUpdate.getUpdateListRequest();
            inValue.Body = new GenAutoUpdate.GenClientAutoUpdate.getUpdateListRequestBody();
            inValue.Body.sDir = sDir;
            GenAutoUpdate.GenClientAutoUpdate.getUpdateListResponse retVal = ((GenAutoUpdate.GenClientAutoUpdate.GenClientAutoUpdateSoap)(this)).getUpdateList(inValue);
            return retVal.Body.getUpdateListResult;
        }
    }
}
